### ISSUE TITLE
Compress in background or seperate isolate?

### ISSUE THREAD

**Issue by aytunch** [AbedElazizShe/light_compressor#1]
Thanks for this great plugin.

I want to know if compressing a long file will make the UI unresponsive?
Is there a way to do this process in another thread?

Thanks

**Comment by AbedElazizShe** [comment]
Thank you for opening the issue. 

The native code for both iOS and Android is running the code in a background thread to ensure it does not block the main thread or cause any app freeze. In Flutter, you just use Futures (async await) to perform that. Just follow the sample code. Please let me know if anthing is not right.

Thank you and feel free to reopen the issue if you face any problems.

**Comment by ShahoodulHassan** [comment]
> Thank you for opening the issue.
> 
> The native code for both iOS and Android is running the code in a background thread to ensure it does not block the main thread or cause any app freeze. In Flutter, you just use Futures (async await) to perform that. Just follow the sample code. Please let me know if anthing is not right.
> 
> Thank you and feel free to reopen the issue if you face any problems.

Would it keep compressing the video even if the app is closed by the user or terminated by the OS?
