### ISSUE TITLE
Do not save the video in the gallery

### ISSUE THREAD

**Issue by NicolasCELLA** [AbedElazizShe/light_compressor#10]
Hello, any idea how to not save the video in the phone gallery?

my code :

```dart
var file;
final tmpDir = await getTemporaryDirectory();

 final Map<String, dynamic> response = await LightCompressor.compressVideo(
          path: _attachement.path,
          destinationPath: '${tmpDir.path}/${DateTime.now().millisecondsSinceEpoch}.mp4',
          videoQuality: VideoQuality.high,
          isMinBitRateEnabled: false,
          keepOriginalResolution: false,
);

if (response['onSuccess'] != null) {
          file = File(response['onSuccess']);
} else if (response['onFailure'] != null) {

 } else if (response['onCancelled'] != null) {
     
}

if (file.existsSync()) {
          file.deleteSync();
}


```

thx for your time 😇

**Comment by Cyphontin** [comment]
Same issue for me on  iOS only. Write a copy of the compressed vidéo in the gallery.

    final Map<String, dynamic>? response = await LightCompressor.compressVideo(
        path: _filePath!,
        destinationPath: _desFile,
        videoQuality: VideoQuality.high,
        isMinBitRateEnabled: false,
        keepOriginalResolution: false
      );

**Comment by NicolasCELLA** [comment]
The problem is in the file "SwiftLightCompressorPlugin.swift"


Just remove:
```swift
DispatchQueue.main.async {
   PHPhotoLibrary.shared().performChanges({
     PHAssetChangeRequest.creationRequestForAssetFromVideo(atFileURL: path)
  })
 }
```

**Comment by Cyphontin** [comment]
It works like a charm. I hope it will be a fixed for futures versions.
Merci Nicolas ca m'a fait gagner beaucoup de temps.

**Comment by AbedElazizShe** [comment]
Thank you for opening the issue and the suggestion to fix it, I added a bool `iosSaveToGallery` to avoid saving, you can just pass it with false.

**Comment by CyriDev** [comment]
Thank you !
