### ISSUE TITLE
Support for custom frame rate

### ISSUE THREAD

**Issue by juanmartin8a** [AbedElazizShe/light_compressor#12]
videos with I high fps are huge in size for example 60 fps. The file size would be smaller with a lower frame rate.

**Comment by Tom3652** [comment]
I was going to ask how is the bitrate lowered ? 
Because when i compress my videos and if the video contains a "zoom" gesture, the resolution is very low
Can we know about the thresholds of the "very_high", "high", "medium", "low", "very_low" please ? 

Thanks for your work

**Comment by AbedElazizShe** [comment]
@juanmartin8a the support for custom framerate is added. If you don't pass one, the framerate of the original video will be chosen instead or 30 if there is any issues. Please close the issue if it works fine with you.

**Comment by AbedElazizShe** [comment]
@Tom3652 it is lowered by reducing the bitrate with a factor based on the quality, for instance, bitrate * 0.6 for `very_high` and * 0.1 for `very_low`

isMinBitRateEnabled was renamed to isMinBitrateCheckEnabled, the library checks if the bitrate is 2mbps or less, it will stop compression. Usually it could be this low if it was compressed before, just to avoid this from happening. 

I don't believe multiple videos will work at the moment, I may add support later, for now, you should wait for one compression's results before starting another.

Thank you, please let me know if you have further questions or feature request.

**Comment by Tom3652** [comment]
Thanks for the reply and the explanations !
