### ISSUE TITLE
Potential crash while compressing 

### ISSUE THREAD

**Issue by Tom3652** [AbedElazizShe/light_compressor#16]
Sometimes i have this error that crashed my app : 

```*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetReader startReading] cannot be called again after reading has already started'``` 

As i really don't know anything about ```Swift```, i have simply checked that on StackOverFlow and they all related to a video compression. 
So if tells you something, please can you explain me why am i seeing this ? 

Thanks a lot in advance

**Comment by AbedElazizShe** [comment]
@Tom3652  at the moment, the library supports a single video compression. Are you compressing multiple videos at the same time?

**Comment by Tom3652** [comment]
Yes actually i was :) In the meantime i have made a queue system to avoid this situation

**Comment by AbedElazizShe** [comment]
Thank you @Tom3652, I will notify you when the multiple videos compression is ready as it requires android and ios work :D

**Comment by Tom3652** [comment]
Thank you for your work ! I have tried the video_compress package and yours is much faster for the same render :)
