### ISSUE TITLE
Android : compressed videos have the images reversed

### ISSUE THREAD

**Issue by mnonga** [AbedElazizShe/light_compressor#19]
Compressed videos have images reversed, as if it was  filmed, so the texts are unreadable. 

After video compression, a person with a right eye will turn into a person a with left eye, as in the following pictures.

Before compression
![Before compression](https://user-images.githubusercontent.com/51037169/144858299-2064a921-8c74-4df7-81fd-6b4919bb5fa0.png).

After compression
![After compression](https://user-images.githubusercontent.com/51037169/144858674-2b34f83f-c3de-4a3b-a849-dee352162f70.png)

Notice how text is now unreadable
![Notice how text is now unreadable](https://user-images.githubusercontent.com/51037169/144858983-f39895bb-bf99-4966-b6b3-7cc6272bfbef.png)

**Comment by jpetro416** [comment]
Seems serious, did you ever confirm or find a fix?
