### ISSUE TITLE
Video trimming capabilities

### ISSUE THREAD

**Issue by DanielFiruClaudiu** [AbedElazizShe/light_compressor#20]
Congratulations for the plug-in, great work! Wondering if you have any plans implementing duration trimming functionality for the compressed video file.

**Comment by AbedElazizShe** [comment]
Hi @DanielFiruClaudiu, thank you for your feedback.

Trimming is a big feature that requires lots of work to be a part of this library. If there is a need for it in flutter, i might build a different plugin. Please confirm if there isn't any useful plugins in flutter that does that.

Thank you.
