### ISSUE TITLE
Android works first time Error 0xffffec77

### ISSUE THREAD

**Issue by sdegenaar** [AbedElazizShe/light_compressor#21]
Hi, when I compress on Android it works fine the first time. If I try again later it always fails with response error Error 0xffffec77.

Any ideas? thanks

**Comment by sdegenaar** [comment]
OK if I wrap it in  Future.delayed(Duration(milliseconds: 300), () async { it seems to work.....

**Comment by thiagocarvalhodev** [comment]
I had the same issue. The problem is I was using the video player while trying to compress the image. What I'm doing is disposing any video player before starting compression.
