### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by sdegenaar** [AbedElazizShe/light_compressor#22]
Hi. when I try and compress a video on Android 11 it crashes the app and I get:-

E/AndroidRuntime( 8556): java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
E/AndroidRuntime( 8556): 	at android.media.MediaMetadataRetriever._setDataSource(Native Method)
E/AndroidRuntime( 8556): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:282)
E/AndroidRuntime( 8556): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:246)
E/AndroidRuntime( 8556): 	at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.compressVideo(Compressor.kt:87)
E/AndroidRuntime( 8556): 	at com.abedelazizshe.lightcompressorlibrary.VideoCompressor$startCompression$2.invokeSuspend(VideoCompressor.kt:114)
E/AndroidRuntime( 8556): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime( 8556): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime( 8556): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
E/AndroidRuntime( 8556): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
E/AndroidRuntime( 8556): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
E/AndroidRuntime( 8556): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
I/Process ( 8556): Sending signal. PID: 8556 SIG: 9

**Comment by DeepikaUdayakumar** [comment]
Same issue occured.  Kindly fix ASAP

**Comment by jpetro416** [comment]
What version of Kotlin are you using?

**Comment by AbedElazizShe** [comment]
Hello, Version 2.0.0 should handle this.

Thank you and sorry for the late response.
