### ISSUE TITLE
During compression sound is removed

### ISSUE THREAD

**Issue by parmeetmaster** [AbedElazizShe/light_compressor#25]
Hello sir

When i successfully got a video after compression.But sound is no more in video please check.

**Comment by AbedElazizShe** [comment]
Hello @parmeetmaster could you please share the device you use ? It could be a device-specific issue. And could you confirm that disableaudio is false?

Thanks a lot.

**Comment by parmeetmaster** [comment]
Sir its solved in new version that i check recently 2.0
