### ISSUE TITLE
Update: Please update the native plugins for light_compressor

### ISSUE THREAD

**Issue by codenameakshay** [AbedElazizShe/light_compressor#26]
## Feature Request
Hey, please update the light_compressor android and iOS native plugins to the latest release, so that features such as setting min-width, height, bitrate are available.

**Comment by dstkdevhrp** [comment]
And also the flutter plugin version. 'Please use Android embedding v2' error when building

**Comment by AbedElazizShe** [comment]
Hello @codenameakshay  and @dstkdevhrp it is done and published.

Thank you and apologies for the late release.
