### ISSUE TITLE
Light Compressor is crashing in android after creating the android build

### ISSUE THREAD

**Issue by tejaswinidev24** [AbedElazizShe/light_compressor#29]
Currently, I am using light_compressor: ^1.2.2

I have added the following dependencies in the app Gradle file
    `implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.3"`
    `implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.3"`
    `implementation 'com.github.AbedElazizShe:LightCompressor:1.0.0'`

and, in the project Gradle file
`maven { url 'https://jitpack.io' }`

`'1.6.10'` is the Kotlin version

Please let me know, how can I resolve this issue.

**Comment by AbedElazizShe** [comment]
Hello @tejaswinidev24, please share some logs to understand why it is crashing. 

Version 2.0.0 is published now, please give it a try and let me know if your issue is fixed.

Thank you.
