### ISSUE TITLE
Getting error "Failed to extract video meta-data, please try again"

### ISSUE THREAD

**Issue by GraSim** [AbedElazizShe/light_compressor#30]
I'm getting the error message "**Failed to extract video meta-data, please try again**" while trying to convert .avi files. Do you have any suggestions on how to fix? Thanks

Device used
Samsung s10 (Android )

**Comment by AbedElazizShe** [comment]
Hello @GraSim, could you please try again with the latest version and let me know if it is still happening ?

Thank you.

**Comment by GraSim** [comment]
I went with another package in the end `ffmpeg_kit_flutter`
