### ISSUE TITLE
Don't ask media permission if video is saved in app storage

### ISSUE THREAD

**Issue by SomeoneAndNoone** [AbedElazizShe/light_compressor#37]
For my users, the video is saved in app specific storage so could you make feature to only ask media files permission when config is save in gallery only?

**Comment by SomeoneAndNoone** [comment]
https://github.com/AbedElazizShe/light_compressor/pull/38

**Comment by AbedElazizShe** [comment]
Hi @SomeoneAndNoone , thank you for opening this and for your PR. The issue was actually fixed in a previous version.
