### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by aghanti7** [AbedElazizShe/light_compressor#4]
compressVideo() fails on iOS with the following error and crashes the app.

```
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file light_compressor/SwiftLightCompressorPlugin.swift, line 50
2020-11-23 21:31:38.271662+0530 Runner[3122:693161] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file light_compressor/SwiftLightCompressorPlugin.swift, line 50
```

**Comment by aghanti7** [comment]
iOS 14 with Flutter 1.22.4 and latest version of plugin

**Comment by AbedElazizShe** [comment]
Thank you for opening the issue, I will fix it and release an update by tomorrow as I don't have access to my Mac now. I will notify you when it is done.

**Comment by AbedElazizShe** [comment]
@aghanti7 please try version 0.0.6 and let me know if the crash is gone. Thank you

**Comment by aghanti7** [comment]
@AbedElazizShe it doesn't crash anymore, but I get `video/quicktime` files with extension `.mov` from the camera, and on compressing that, the audio is retained, but the video is blacked out.

**Comment by aghanti7** [comment]
Actually, I was able to play the compressed quicktime/mov video file on an Android phone. So, let me check the video player on iOS and get back to you.

**Comment by aghanti7** [comment]
Ok. Here is the present problem.

1. I take a video using image_picker on iOS, and upload it to cloud - it works fine (plays on both iOS and Android)
2. I take a video using image_picker on iOS, compress it using this plugin, and upload to cloud - it plays fine on Android, but on iOS I only get a black screen (audio plays).

In both cases it is a quicktime .mov file.

**Comment by kadnan0900** [comment]
@aghanti7 Is this library that much mature that i would use in production app ?

**Comment by aghanti7** [comment]
@kadnan0900 tried a lot of other plugins - they either just downsample (reduce only resolution) or use a heavy library like ffmpeg. This plugin resamples the video by reducing both bitrate and resolution. I don't think the process is so complex.

Also, as long as @AbedElazizShe is responsive in fixing bugs, I would use it!

**Comment by kadnan0900** [comment]
@aghanti7 please updat on this when this library that much stable to use in production app.As you said others library is too much heavy and make's app size bigger.now i am following this library.

**Comment by AbedElazizShe** [comment]
@aghanti7 @kadnan0900 Thank you for your feedback, comments like that would always help to improve these kind of plugin that would benefit everyone and hopefully attract people to contribute. 

As you know, this plugin is based on a project I started in Android to have a lightweight and a decent library to use in my projects and I have been improving it ever since. Recently, I have been getting the exact same issue from multiple developers that the compressed video from a short list of phones (like pixel 3 to pixel 5) don't play on mac/iphone using quicktime only, if you play the video on vlc for instance, it will play just fine. @aghanti7 **I believe in your second point you mean Android**

I have been investigating (for more than 2 months now) and trying to understand why quicktime fails to play the video compressed from those devices, but no luck until now. I will spend more time and hopefully find a fix soon.

**Comment by aghanti7** [comment]
> As you know, this plugin is based on a project I started in Android to have a lightweight and a decent library to use in my projects and I have been improving it ever since. Recently, I have been getting the exact same issue from multiple developers that the compressed video from a short list of phones (like pixel 3 to pixel 5) don't play on mac/iphone using quicktime only, if you play the video on vlc for instance, it will play just fine. @aghanti7 **I believe in your second point you mean Android**

Hello @AbedElazizShe ... I mean iOS only - I take a quicktime/mov video on iPhone, it plays using video_player. I then compress it using this plugin, video_player shows black screen and only audio - all this on iOS.

**Comment by AbedElazizShe** [comment]
@aghanti7 Thank you for clarifying that, I will have a look at that and have a fix as soon as possible. Sorry misread the issue.
Thank you :D

**Comment by AbedElazizShe** [comment]
@aghanti7 Just a question so I can create a similar environment to test. Where do you upload the video and how do you play the video? Services names or which kind of cloud would be very helpful.

**Comment by aghanti7** [comment]
> @aghanti7 Just a question so I can create a similar environment to test. Where do you upload the video and how do you play the video? Services names or which kind of cloud would be very helpful.

No need to upload the video @AbedElazizShe ... I captured the video from camera using image_picker and compressed it locally - issue still happens.

**Comment by AbedElazizShe** [comment]
Alright then, which iphone(s) and ios version?

**Comment by aghanti7** [comment]
iPhone 7 - iOS 14.2

**Comment by kadnan0900** [comment]
@AbedElazizShe please update when you fix that crash.

**Comment by NicolasCELLA** [comment]
same issue 😕

**Comment by AbedElazizShe** [comment]
Sorry for late reply.

I just released a new version 0.0.7 with bugs fixes, I tested on iPhone 12 - ios 14.2 and everything is working fine. However, there is an important change the should be done. `Replace image_picker`; the plugin has a very weird bug, the selected video has jpg format, here is the open issue https://github.com/flutter/flutter/issues/52419.

There was another problem that the plugin failed to handle which is a video that has no sound track (such as recording a video while disabling microphone), it should work now without a crash.

Please update the plugin and let me know if you still have a problem and look at the sample app to see how you can use file_picker instead of image_picker.

**Comment by aghanti7** [comment]
> > @aghanti7 Just a question so I can create a similar environment to test. Where do you upload the video and how do you play the video? Services names or which kind of cloud would be very helpful.
> 
> No need to upload the video @AbedElazizShe ... I captured the video from camera using image_picker and compressed it locally - issue still happens.

Hi @AbedElazizShe thanks for the update. But in bug https://github.com/flutter/flutter/issues/52419 they talk about picking a video from gallery. In my case (refer quoted reply above) I get a QuickTime mov file from iOS, using image_picker with source camera. Can you test this use case and let me know please?

**Comment by kadnan0900** [comment]
@aghanti7 did you test the update ?

**Comment by aghanti7** [comment]
> @aghanti7 did you test the update ?

Not yet. Will do later tonight.

**Comment by aghanti7** [comment]
@AbedElazizShe the fix is not working (I am still using image_picker.getVideo(source: ImageSource.camera)

1. Bug https://github.com/flutter/flutter/issues/52419 talks about picking a video from gallery, not camera.
2. Not possible with file_picker to select from camera source

**Comment by aghanti7** [comment]
@AbedElazizShe any updates?

**Comment by aghanti7** [comment]
@AbedElazizShe any updates?

**Comment by AbedElazizShe** [comment]
@aghanti7 I am sorry for the late reply. I tested the sample app on iPhone 7 - iOS 14.2 and iOS 14.3, and I can't reproduce the issue, everything seems fine on my side. Please create a sample app and share a link with me so I can figure out the issue, I'd appriciate that.

**Comment by AbedElazizShe** [comment]
@aghanti7 @NicolasCELLA @kadnan0900 I have been testing on multiple iphones including SE and X. I am totaly unable to reproduce the issue. Please help me understand more by posting a video showing the scenario or share a sample app github link where I can see and fix the issue. Thank you

**Comment by AbedElazizShe** [comment]
Will close this issue due to inactivity, assuming the issue is not happening anymore, feel free to reopen.

**Comment by aghanti7** [comment]
Sorry for the extremely delayed reply @AbedElazizShe . The issue is fixed now. Thank you very much!
