### ISSUE TITLE
Release mode fails on android

### ISSUE THREAD

**Issue by arashbi** [AbedElazizShe/light_compressor#7]
When I try to run the example application on android in release mode - `flutter run --release`; it gives me an exception 

> Flutter run key commands.
h Repeat this help message.
c Clear the screen
q Quit (terminate the application on the device).
I/flutter ( 7589): MissingPluginException(No implementation found for method listen on channel compression/stream)
I/flutter ( 7589): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
I/flutter ( 7589): <asynchronous suspension>
I/flutter ( 7589): #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:545)
I/flutter ( 7589): <asynchronous suspension>

And the application freezes after selecting a video

**Comment by AbedElazizShe** [comment]
@arashbi have you tried to add  the following to app/build.gradle release build type configuration ?
        shrinkResources false
         minifyEnabled false

**Comment by arashbi** [comment]
No, I was just trying to see what is the maximum speed I can get from it.  It doesn't seem too fast. A one minute video takes like 40 second to finish compression.
I wonder how telegram application manages to compress video in a short time

**Comment by arashbi** [comment]
In telegram, after picking a video,  you can press the gear button, and
choose the compression level
