### ISSUE TITLE
Example App video is not working on iOS Devices

### ISSUE THREAD

**Issue by Letalus** [AbedElazizShe/light_compressor#8]
Hello everyone,

following is the case:
1. I start the app on an IPhone 11
2. I select a video 
3. It starts compressing
4. When I click on the "Play video" button only a black screen will be shown with sound
5. No error appears, yet it is not working

--> Review video for more information

https://user-images.githubusercontent.com/41230136/114992365-f7887700-9e9a-11eb-812d-09ac5b034799.MP4

**Comment by AbedElazizShe** [comment]
@Letalus thank you for opening this. Can you check if the compressed file is generated and working fine in your device's video player? The sample app is using a plugin to run the video and it might have some issues. If your video plays fine with the video player like vlc for example, then that would narrow down what the issue might be and I will replace the flutter plugin.

**Comment by NicolasCELLA** [comment]
Same problem with video recording with my iphone.

Video have no problem with other video player

**Comment by NicolasCELLA** [comment]
UPDATE:

The problem comes from the video taken in portrait.
The height and width information is not correct

<img width="393" alt="Capture d’écran 2021-05-20 à 13 35 29" src="https://user-images.githubusercontent.com/27723625/118972089-7415e600-b970-11eb-811d-5b23327a9704.png">

**Comment by NicolasCELLA** [comment]
The problem is from video_player.
https://github.com/flutter/plugins/pull/1307

this issue fix the problem 👌
