### ISSUE TITLE
iOS App is force closing once the compressVideo method is called

### ISSUE THREAD

**Issue by Letalus** [AbedElazizShe/light_compressor#9]
I have a picked video from the image picker. Now once I call LightCompressor.compressVideo following error appears and force closes the app:

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetReader startReading] cannot be called again after reading has already started'
*** First throw call stack:
(0x19d2b186c 0x1b22cac50 0x1a4df1fe8 0x10498f040 0x10498f4c0 0x10498f570 0x19cea424c 0x19cea5db0 0x19cead10c 0x19ceadc5c 0x19ceb7d78 0x1e8d5d814 0x1e8d6476c)
libc++abi.dylib: terminating with uncaught exception of type NSException
* thread #61, queue = 'processingQueue1', stop reason = signal SIGABRT
    frame #0: 0x00000001cb201414 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1cb201414 <+8>:  b.lo   0x1cb201434               ; <+40>
    0x1cb201418 <+12>: pacibsp 
    0x1cb20141c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1cb201420 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.`

**Comment by AbedElazizShe** [comment]
@Letalus thank you for opening this issue and sorry for the late reply. I am working on this issue which was reported in the swift package https://github.com/AbedElazizShe/LightCompressor_iOS/issues/1. I will notify here when fixed.

**Comment by Letalus** [comment]
hey @AbedElazizShe thanks for the update. It seems like the issue has been fixed within the iOS side. Have you been already able to export those fixes to the flutter package? Thanks again for your effort.

Kind regards,
Chris
